title: Le Mallouestan

plugins:
  - jekyll-bookshop
  - cloudcannon-jekyll-bookshop
  - jekyll-sitemap
  - jekyll-pagebreak

# Multiple bookshops can be used on one website,
# or different production / staging locations.
bookshop_locations:
  - ../components

exclude:
  - postcss.config.js
  - node_modules

include:
  - _cloudcannon

baseurl: "/site"

# The rest of this array structure will be
# populated by the bookshop-array-structures plugin.
_array_structures:
  content_blocks:
    style: modal

collections_dir: 'collections'

collections:
  pages:
    output: true
    permalink: /:title/
  inhabitants:
    output: true
    permalink: /inhabitants/:slug
  ressources:
    output: true
    permalink: /ressources/:slug
  events:
    output: true
    permalink: /events/:slug
  tags:
    output: true
    permalink: /tag/:slug

_collection_groups:
  - heading: Content
    collections:
      - pages
      - inhabitants
      - events
  - heading: Blogging
    collections:
      - ressources
      - drafts
      - tags
  - heading: Settings
    collections:
      - data

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: pages
      path: _pages/index.html
    values:
      permalink: /
  - scope:
      type: inhabitants
    values:
      layout: project
  - scope:
      type: events
    values:
      layout: project
  - scope:
      type: ressources
    values:
      layout: post
  - scope:
      type: tags
    values:
      layout: tag_page

